version: '3.9'

services:
  db:
    image: postgres:14
    container_name: kara_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: kara_app
    depends_on:
      - db
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
